### ISSUE TITLE
Is this app Revolut TOS compatible?

### ISSUE THREAD

**Issue by Jancis** [Annihil/revolut-emergency#3]
First of all - You've done a stellar work for open source community here, thank You :clap: ! I'd love to try this, but since i've seen quite a few frozen account complaints in reddit (not related to this app, as far as i know), i am slightly cautious to run this. 

Is there any chance you could contact revolut representative and make sure this app is legal to use and does not void any TOS? Add this to `README.md` so people know. Just so there are no surprises.

**Comment by Annihil** [comment]
Hi,
Thank you for the kind words 😊
I am not sure about the ToS compliance, but they are aware of it and I haven't been contacted by them for violation.
Since the network requests are similar to the ones sent by the mobile app, it would be hard for Revolut to tell it is coming from this electron app.

**Comment by Jancis** [comment]
I'm sure they could send a control request along with the original if they'd be against this app eventually, to find out who is using them, but if you have not had any threats from them, then it should be fine ;) 
Thanks!
